"""Shared employment taxonomy used by search, profiles, and job posting forms."""

JOB_CATEGORIES = [
    "Technology & IT",
    "Business, Administration & Operations",
    "Finance & Accounting",
    "Sales, Marketing & Customer Service",
    "Human Resources",
    "Education & Childcare",
    "Healthcare",
    "Hospitality, Food & Restaurants",
    "Cleaning & Domestic Services",
    "Driving, Logistics & Delivery",
    "Retail",
    "Security",
    "Construction & Skilled Trades",
    "Automotive",
    "Beauty & Fashion",
    "Agriculture",
    "NGO, Development & Research",
    "Media & Creative",
    "Legal",
    "Property & Real Estate",
    "Manufacturing & Factory",
    "Entry-Level & No-Degree Jobs",
]

JOB_TITLES = [
    "Software Developer", "Frontend Developer", "Backend Developer", "Full-Stack Developer",
    "Mobile App Developer", "Android Developer", "iOS Developer", "Web Developer",
    "WordPress Developer", "Software Engineer", "DevOps Engineer", "Cloud Engineer",
    "Data Engineer", "Data Analyst", "Data Scientist", "AI Engineer", "Machine Learning Engineer",
    "Cybersecurity Analyst", "Security Engineer", "Network Engineer", "Systems Administrator",
    "Database Administrator", "IT Support Officer", "IT Technician", "Help Desk Officer",
    "Technical Support Specialist", "QA Engineer", "Software Tester", "UI Designer", "UX Designer",
    "UI/UX Designer", "Product Designer", "Business Analyst", "Systems Analyst", "Solutions Architect",
    "Technical Writer", "IT Project Manager", "Scrum Master", "Administrative Assistant",
    "Administrative Officer", "Office Assistant", "Office Administrator", "Executive Assistant",
    "Personal Assistant", "Secretary", "Receptionist", "Front Desk Officer", "Operations Assistant",
    "Operations Officer", "Operations Manager", "Business Development Officer", "Business Development Manager",
    "Project Assistant", "Project Officer", "Project Coordinator", "Project Manager", "Programme Assistant",
    "Programme Officer", "Programme Coordinator", "Procurement Officer", "Supply Chain Officer",
    "Logistics Officer", "Inventory Officer", "Storekeeper", "Warehouse Officer", "Data Entry Clerk",
    "Document Controller", "Accountant", "Accounting Assistant", "Account Officer", "Finance Assistant",
    "Finance Officer", "Finance Manager", "Auditor", "Internal Auditor", "Bookkeeper", "Payroll Officer",
    "Tax Officer", "Credit Officer", "Loan Officer", "Bank Teller", "Financial Analyst", "Investment Analyst",
    "Treasury Officer", "Billing Officer", "Cashier", "Sales Representative", "Sales Executive",
    "Sales Associate", "Sales Officer", "Sales Manager", "Business Development Representative",
    "Telesales Agent", "Telemarketer", "Customer Service Representative", "Customer Support Officer",
    "Customer Success Officer", "Call Centre Agent", "Contact Centre Agent", "Digital Marketer",
    "Marketing Assistant", "Marketing Officer", "Marketing Executive", "Brand Executive", "Brand Manager",
    "Social Media Manager", "Social Media Assistant", "Content Creator", "Content Writer", "Copywriter",
    "SEO Specialist", "Email Marketing Specialist", "Growth Marketer", "Community Manager",
    "Communications Officer", "Public Relations Officer", "HR Assistant", "HR Officer", "HR Executive",
    "HR Manager", "Recruiter", "Recruitment Officer", "Talent Acquisition Specialist", "Training Coordinator",
    "Employee Relations Officer", "Teacher", "Teaching Assistant", "Nursery Teacher", "Primary School Teacher",
    "Secondary School Teacher", "Mathematics Teacher", "English Teacher", "Science Teacher", "Tutor",
    "Online Tutor", "Lecturer", "Graduate Assistant", "School Administrator", "Librarian", "Nanny",
    "Medical Doctor", "Nurse", "Registered Nurse", "Healthcare Assistant", "Caregiver", "Pharmacy Assistant",
    "Pharmacist", "Laboratory Technician", "Medical Laboratory Scientist", "Physiotherapist", "Nutritionist",
    "Community Health Worker", "Medical Receptionist", "Dental Assistant", "Hotel Receptionist", "Hotel Attendant",
    "Housekeeper", "Room Attendant", "Cleaner", "Janitor", "Waiter", "Waitress", "Server", "Bartender",
    "Barista", "Cook", "Chef", "Kitchen Assistant", "Kitchen Porter", "Dishwasher", "Restaurant Supervisor",
    "Restaurant Manager", "Hotel Manager", "Catering Assistant", "Baker", "Pastry Chef", "Office Cleaner",
    "Residential Cleaner", "Commercial Cleaner", "Industrial Cleaner", "Hospital Cleaner", "School Cleaner",
    "Domestic Assistant", "Laundry Attendant", "Car Wash Attendant", "Waste Collector", "Driver",
    "Personal Driver", "Company Driver", "Truck Driver", "Bus Driver", "Dispatch Rider", "Delivery Rider",
    "Delivery Driver", "Courier", "Logistics Assistant", "Logistics Coordinator", "Warehouse Assistant",
    "Warehouse Operative", "Loader", "Packer", "Picker", "Forklift Operator", "Transport Officer",
    "Fleet Officer", "Fleet Manager", "Shop Assistant", "Shop Attendant", "Sales Attendant", "Retail Assistant",
    "Store Assistant", "Merchandiser", "Supermarket Attendant", "Shelf Stocker", "Inventory Assistant",
    "Security Guard", "Security Officer", "Security Supervisor", "CCTV Operator", "Gatekeeper",
    "Construction Worker", "Labourer", "Site Assistant", "Site Supervisor", "Civil Engineer", "Mechanical Engineer",
    "Electrical Engineer", "Architect", "Electrician", "Plumber", "Carpenter", "Welder", "Bricklayer",
    "Mason", "Painter", "Tiler", "Roofer", "AC Technician", "Generator Technician", "Solar Installer",
    "Solar Technician", "Mechanic", "Auto Mechanic", "Auto Electrician", "Vehicle Technician", "Tyre Technician",
    "Car Detailer", "Motorcycle Mechanic", "Hair Stylist", "Barber", "Braider", "Makeup Artist",
    "Nail Technician", "Beautician", "Tailor", "Fashion Designer", "Seamstress", "Farm Worker",
    "Farm Assistant", "Farm Manager", "Agricultural Officer", "Agronomist", "Poultry Worker", "Livestock Assistant",
    "Fisheries Officer", "Field Assistant", "Tractor Operator", "Research Assistant", "Research Officer",
    "Research Associate", "Field Officer", "Field Enumerator", "Data Collector", "Survey Enumerator",
    "Monitoring and Evaluation Officer", "MEAL Officer", "Grant Officer", "Grants Manager", "Partnership Officer",
    "Community Mobilizer", "Policy Analyst", "Graphic Designer", "Video Editor", "Photographer", "Videographer",
    "Animator", "Motion Graphics Designer", "Journalist", "Reporter", "Editor", "Proofreader", "Scriptwriter",
    "Production Assistant", "Lawyer", "Legal Assistant", "Legal Officer", "Paralegal", "Compliance Officer",
    "Real Estate Agent", "Property Manager", "Facility Manager", "Estate Officer", "Leasing Officer",
    "Factory Worker", "Production Worker", "Production Assistant", "Machine Operator", "Packaging Assistant",
    "Quality Control Assistant", "Quality Assurance Officer", "Production Supervisor", "Maintenance Technician",
    "Assembly Worker", "Apprentice", "Mechanic Assistant", "Electrician Assistant", "Plumbing Assistant",
    "Barber Assistant", "Salon Assistant", "Tailoring Assistant", "Promoter", "Event Usher", "Brand Ambassador",
]

ENTRY_LEVEL_TITLES = [
    "Cleaner", "Housekeeper", "Janitor", "Office Assistant", "Office Cleaner", "Shop Attendant",
    "Sales Attendant", "Cashier", "Receptionist", "Front Desk Assistant", "Driver", "Dispatch Rider",
    "Delivery Rider", "Delivery Driver", "Warehouse Assistant", "Loader", "Packer", "Store Assistant",
    "Kitchen Assistant", "Waiter", "Waitress", "Fast Food Attendant", "Dishwasher", "Laundry Attendant",
    "Car Wash Attendant", "Security Guard", "Gatekeeper", "Daycare Assistant", "Babysitter", "Nanny",
    "Caregiver", "Farm Worker", "Factory Worker", "Production Assistant", "Construction Labourer",
    "Apprentice", "Mechanic Assistant", "Electrician Assistant", "Plumbing Assistant", "Barber Assistant",
    "Salon Assistant", "Tailoring Assistant", "Data Entry Clerk", "Call Centre Agent", "Customer Service Agent",
    "Field Enumerator", "Promoter", "Event Usher", "Brand Ambassador",
]

SKILLS = [
    "Microsoft Word", "Microsoft Excel", "Microsoft PowerPoint", "Google Docs", "Google Sheets", "Google Workspace",
    "Data Entry", "Typing", "Internet Research", "Email Management", "Canva", "Graphic Design", "Adobe Photoshop",
    "Adobe Illustrator", "Figma", "HTML", "CSS", "JavaScript", "TypeScript", "React", "Next.js", "Vue.js",
    "Angular", "Node.js", "Python", "Java", "C#", "C++", "PHP", "Laravel", "SQL", "MySQL", "PostgreSQL",
    "MongoDB", "Git", "GitHub", "AWS", "Azure", "Docker", "Kubernetes", "Power BI", "Tableau", "R",
    "SPSS", "Machine Learning", "Artificial Intelligence", "Data Analysis", "Data Visualization", "Cybersecurity",
    "Networking", "WordPress", "SEO", "Sales", "Customer Service", "Business Development", "Lead Generation",
    "Negotiation", "Account Management", "CRM", "Zoho CRM", "Salesforce", "HubSpot", "Project Management",
    "Operations Management", "Inventory Management", "Procurement", "Supply Chain Management", "Logistics",
    "Bookkeeping", "Accounting", "Payroll", "Financial Reporting", "Budgeting", "Auditing", "Communication",
    "Teamwork", "Leadership", "Problem Solving", "Critical Thinking", "Time Management", "Organisation",
    "Attention to Detail", "Multitasking", "Adaptability", "Creativity", "Customer Relations", "Presentation Skills",
    "Report Writing", "Driving", "Motorcycle Riding", "Cleaning", "Housekeeping", "Cooking", "Baking", "Childcare",
    "Elderly Care", "Hairdressing", "Braiding", "Barbering", "Tailoring", "Sewing", "Makeup", "Nail Care",
    "Carpentry", "Plumbing", "Electrical Installation", "Welding", "Painting", "Tiling", "Masonry", "Auto Repair",
    "Generator Repair", "Solar Installation", "Farming", "Poultry Farming", "Fish Farming", "Forklift Operation",
    "Machine Operation",
]

EMPLOYMENT_TYPES = [
    "Full-time", "Part-time", "Temporary", "Contract", "Freelance", "Internship", "Graduate Trainee",
    "Apprenticeship", "Industrial Training (IT/SIWES)", "NYSC Placement", "Volunteer", "Seasonal Work",
]

EXPERIENCE_LEVELS = [
    "No Experience Required", "Entry Level", "Internship", "Apprentice/Trainee", "1-2 Years", "2-3 Years",
    "3-5 Years", "5-7 Years", "7-10 Years", "10+ Years", "Mid-Level", "Senior Level", "Manager",
    "Director/Executive",
]

EDUCATION_LEVELS = [
    "No Formal Education", "Primary School", "Junior Secondary", "SSCE/WAEC/NECO", "Vocational Training",
    "Trade Test", "Certificate", "OND", "NCE", "HND", "Bachelor's Degree", "Postgraduate Diploma",
    "Master's Degree", "PhD", "Professional Certification", "Student/Undergraduate", "NYSC Member",
    "Recent Graduate", "Not Required",
]

INDUSTRIES = [
    "Banking", "Fintech", "Insurance", "Technology", "Telecommunications", "Consulting", "Accounting",
    "Education", "Healthcare", "Pharmaceutical", "NGO/Nonprofit", "Government", "Agriculture", "Food Processing",
    "Manufacturing", "Construction", "Engineering", "Oil & Gas", "Energy", "Renewable Energy", "Mining",
    "Logistics", "Transportation", "Aviation", "Maritime", "Hospitality", "Hotels", "Restaurants", "Retail",
    "E-commerce", "Fashion", "Beauty", "Media", "Advertising", "Entertainment", "Real Estate",
    "Facility Management", "Security Services", "Cleaning Services", "Automotive", "Legal Services", "Research",
    "International Development", "FMCG", "Professional Services",
]

WORKPLACE_TYPES = ["Remote", "Hybrid", "Onsite"]
COUNTRIES = ["United States", "Canada", "Mexico", "Germany", "United Kingdom"]
